"""UP/DOWN symmetry check. In US/India true records, number moved UP 1-20 and DOWN 1-20 happen about equally often
(number typo noise); decoys move UP. So in France the count of pairs with the number moved DOWN (same name-change
type) estimates the number of TRUE pairs with the number moved UP."""
import polars as pl
pl.Config.set_tbl_rows(80); pl.Config.set_tbl_width_chars(250); pl.Config.set_fmt_str_lengths(40)
F = 'C:/Users/kanav/.claude/jobs/ef6f152d/tmp/frfix2/fp/'
u = pl.read_parquet(F + 'usi_sig.parquet', columns=['q', 'grp', 'country', 'p', 'base', 'numc', 'num', 'low'])
fr = pl.read_parquet(F + 'fr_sig.parquet', columns=['q', 's', 'p2', 'acc9', 'veto', 'gadd', 'numc', 'num', 'low', 'base', 'nchg'])
nm = pl.col('base').str.split('+')
def cls(d):
    return d.with_columns(k=pl.when(nm.list.contains('LEGAL_ADD')).then(pl.lit('A:LEGAL_ADD*'))
                          .when(nm.list.eval(pl.element().is_in(['ADD', 'SWAP', 'TYPO', 'LEGAL_CHANGE'])).list.any()
                                & ~nm.list.eval(pl.element().is_in(['DROP', 'DUP'])).list.any()).then(pl.lit('B:add/swap/typo'))
                          .when(pl.col('base') == '').then(pl.lit('none'))
                          .otherwise(pl.lit('other')))
u = cls(u); fr = cls(fr)
print('== US/India TRUE records: count by class x numc (UP vs DOWN small)')
t = u.filter(pl.col('grp') == 'T').group_by('country', 'k', 'numc').len().pivot(on='numc', index=['country', 'k'], values='len').sort('country', 'k')
print(t.select('country', 'k', 'NSAME', 'UP', 'DOWN', 'UPbig', 'DOWNbig'))
print('== US/India FALSE (D+W) records by class x numc')
t = u.filter(pl.col('grp') != 'T').group_by('country', 'k', 'numc').len().pivot(on='numc', index=['country', 'k'], values='len').sort('country', 'k')
print(t.select('country', 'k', 'NSAME', 'UP', 'DOWN', 'UPbig', 'DOWNbig'))
print('== France ALL best-candidate pairs by class x numc')
t = fr.group_by('k', 'numc').len().pivot(on='numc', index='k', values='len').sort('k')
print(t.select('k', 'NSAME', 'UP', 'DOWN', 'UPbig', 'DOWNbig'))
print('== France ACCEPTED v9b by class x numc')
t = fr.filter(pl.col('acc9')).group_by('k', 'numc').len().pivot(on='numc', index='k', values='len').sort('k')
print(t.select('k', 'NSAME', 'UP', 'DOWN', 'UPbig', 'DOWNbig'))
print('== France accepted lowercase share by class x numc')
t = fr.filter(pl.col('acc9')).group_by('k', 'numc').agg(pl.col('low').mean()).pivot(on='numc', index='k', values='low').sort('k')
print(t.select('k', 'NSAME', 'UP', 'DOWN', 'UPbig', 'DOWNbig'))
print('== France REJECTED (not vetoed) lowercase share by class x numc')
t = fr.filter(~pl.col('acc9') & ~pl.col('veto')).group_by('k', 'numc').agg(pl.col('low').mean()).pivot(on='numc', index='k', values='low').sort('k')
print(t.select('k', 'NSAME', 'UP', 'DOWN', 'UPbig', 'DOWNbig'))
print('== pure LEGAL_ADD: France all / accepted by num detail')
print(fr.filter(pl.col('base') == 'LEGAL_ADD').group_by('num').agg(n=pl.len(), acc=pl.col('acc9').sum(), low_acc=pl.col('low').filter(pl.col('acc9')).mean(), low_rej=pl.col('low').filter(~pl.col('acc9')).mean()).sort('n', descending=True))
print('== pure LEGAL_ADD: US/India by num detail, T vs F')
print(u.filter(pl.col('base') == 'LEGAL_ADD').group_by('country', 'num').agg(n=pl.len(), T=(pl.col('grp') == 'T').sum()).sort('country', 'n', descending=True))
